services:
  app:
    build: .
    container_name: mytradersystem-app
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - poetry_venv:/workspace/.venv
    command: sh -c "tail -f /dev/null"
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      - POETRY_NO_INTERACTION=1
    tty: true
  webUI:
    build: .
    image: mytradersystem-webui
    container_name: mytradersystem-webui
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - poetry_venv:/workspace/.venv
    command: sh -c "/workspace/.venv/bin/python -m app.controlplane.api --env dev --host 0.0.0.0 --port 8000"
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      - POETRY_NO_INTERACTION=1
    ports:
      - "8000:8000"
    depends_on:
      - app
  control-plane-worker:
    build: .
    container_name: mytradersystem-control-plane-worker
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - poetry_venv:/workspace/.venv
    command: sh -c "/workspace/.venv/bin/python -m app.controlplane.worker --env dev"
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      - POETRY_NO_INTERACTION=1
    depends_on:
      - app

volumes:
  poetry_venv:
